global:
  storageClass: "longhorn-balanced"

indexer:
  replicas: 3

certificates:
  selfSigned: false
  duration: 2160h
  renewBefore: 720h
  issuerRef:
    name: wazuh-vault-issuer
    kind: ClusterIssuer
  rootCA:
    secretName: vault-ca-bundle
  subject:
    organizations:
      - "Techlab"
    organizationalUnits:
      - "Wazuh"
    localities:
      - "Utah"
    countries:
      - "US"

secrets:
  indexerUsername: "indexeradmin"
  indexerPassword: "IndexPass123!"
  indexerPasswordHash: "$2y$12$5LRgiIzbfIMntpZFJ7EmiuHrsJqnOHtHXIg0wMK7Mv7N3mwj/HiTe"
  dashboardUsername: "wazuh-dashboard"
  dashboardPassword: "WazuhDash123!"
  dashboardPasswordHash: "$2y$12$02JBI44WAyGfSo.FqoWdJOXPrrIxFXDDADr0BjmbrfA/D8g933s3q"
